<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>

<table id="albums" class="table table-striped">
    <tr>
        <th >Title</th>
        <th >Artist</th>
        <th >Year</th>
        <th colspan="2" >Actions</th>
    </tr>
    <?php foreach($this->albums as $album) : ?>
        <tr>
            <td><?php echo $this->escape($album->title);?></td>
            <td><?php echo $this->escape($album->artist);?></td>
            <td><?php echo $this->escape($album->year);?></td>
            <td>
               <button><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$album->id));?>">Edit</a> </button>
               <button><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$album->id));?>">Delete</a></button>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

    <p><a href="<?php echo $this->url(array('controller'=>'index', 'action'=>'add'));?>">Add new album</a></p> <br />

<?php
//$db = mysql_connect ("localhost", "root", "qweqwe");
//if ($db == true) {
//    echo 'True';
//} else echo 'False';
//?>