<?php
$this->title = "Items";
$this->headTitle($this->title);
?>

<table>
    <tr>
        <th>Name</th>
        <th >Email</th>
        <th >Telephone</th>
        <th >Title</th>
        <th >Year</th>
        <th >Denomination</th>
        <th >MinPrice</th>
        <th >MaxPrice</th>
        <th >Description</th>
    </tr>
    <?php foreach($this->items as $item) : ?>
        <tr>
            <td><?php echo $this->escape($item->name);?></td>
            <td><?php echo $this->escape($item->email);?></td>
            <td><?php echo $this->escape($item->tel);?></td>
            <td><?php echo $this->escape($item->title);?></td>
            <td><?php echo $this->escape($item->year);?></td>
            <td><?php echo $this->escape($item->denomination);?></td>
            <td><?php echo $this->escape($item->priceMin);?></td>
            <td><?php echo $this->escape($item->priceMax);?></td>
            <td><?php echo $this->escape($item->notes);?></td>

<!--            <td>-->
<!--                <button><a href="--><?php //echo $this->url(array('controller'=>'index', 'action'=>'edit', 'id'=>$album->id));?><!--">Edit</a> </button>-->
<!--                <button><a href="--><?php //echo $this->url(array('controller'=>'index', 'action'=>'delete', 'id'=>$album->id));?><!--">Delete</a></button>-->
<!--            </td>-->
        </tr>
    <?php endforeach; ?>
</table>

<button autofocus="next"><a href="<?php echo $this->url(array('controller' => 'item', 'action' => 'add')) ?>">Add item</a></button>
<button accesskey="1" onclick="alert('Зачем нажал кнопку 1')">1</button>
<input required placeholder="NAME">