CREATE TABLE users (
id INT(11) NOT NULL AUTO_INCREMENT,
firstname VARCHAR(100) DEFAULT NULL,
lastname VARCHAR(100) DEFAULT NULL,
email VARCHAR(200) NOT NULL,
username VARCHAR(100) NOT NULL,
password VARCHAR(32) NOT NULL,
PRIMARY KEY(id)
);